AppName: test-app
image:
  repository: 740183721899.dkr.ecr.us-east-1.amazonaws.com
namespace: dev
containerPort: 3000
resources:
  requests:
    cpu: 0.5
    memory: 500Mi
  limits:
    cpu: 1
    memory: 1Gi
ingress:
  enabled: true
  host: app.example.com